import { RANKS } from '@/features/ranks/rankUtils';
import type { ShopItem, ShopRankRequirement, ShopSection } from './shopTypes';

const itemImagePath = '/assets/shop/items/';

export const SHOP_SECTIONS: ShopSection[] = [
  {
    arsenalName: 'Core Shop',
    description: 'Foundational tools for extra challenges, XP boosts, and streak protection.',
    id: 'core',
    rankRequirement: 'core',
    title: 'Core Shop',
    items: [
      {
        cost: 250,
        effect: 'Generate one additional daily challenge today.',
        id: 'bonus-challenge-scroll',
        image: `${itemImagePath}bonus-challenge-scroll.png`,
        kind: 'utility',
        name: 'Bonus Challenge Scroll',
        rankRequirement: 'core',
        repeatable: true,
      },
      {
        cost: 500,
        effect: 'Your next completed challenge grants double XP.',
        id: 'double-xp-sigil',
        image: `${itemImagePath}double-xp-sigil.png`,
        kind: 'boost',
        name: 'Double XP Sigil',
        rankRequirement: 'core',
        repeatable: true,
      },
      {
        cost: 300,
        effect: 'For 24 hours, get +20% XP from Focus challenges.',
        id: 'focus-lens',
        image: `${itemImagePath}focus-lens.png`,
        kind: 'boost',
        name: 'Focus Lens',
        rankRequirement: 'core',
        repeatable: true,
      },
      {
        cost: 300,
        effect: 'For 24 hours, get +20% XP from Health challenges.',
        id: 'iron-will-token',
        image: `${itemImagePath}iron-will-token.png`,
        kind: 'boost',
        name: 'Iron Will Token',
        rankRequirement: 'core',
        repeatable: true,
      },
      {
        cost: 300,
        effect: 'For 24 hours, get +20% XP from Growth challenges.',
        id: 'scholars-seal',
        image: `${itemImagePath}scholars-seal.png`,
        kind: 'boost',
        name: "Scholar's Seal",
        rankRequirement: 'core',
        repeatable: true,
      },
      {
        cost: 1500,
        effect: 'Protect your streak once; consumed when a missed day would break it.',
        id: 'streak-shield',
        image: `${itemImagePath}streak-shield.png`,
        kind: 'protection',
        name: 'Streak Shield',
        rankRequirement: 'core',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Disciple Arsenal',
    description: 'Early challenge modification tools for players who reached D Rank.',
    id: 'd-rank',
    rankRequirement: 'D',
    title: 'D Rank Arsenal',
    items: [
      {
        cost: 500,
        effect: 'Replace one easy daily challenge with a harder version for higher XP and Essence rewards.',
        id: 'elite-contract',
        image: `${itemImagePath}elite-contract.png`,
        kind: 'contract',
        name: 'Elite Contract',
        rankRequirement: 'D',
        repeatable: true,
      },
      {
        cost: 350,
        effect: 'Replace one active daily challenge with a new random daily challenge.',
        id: 'challenge-reroll-token',
        image: `${itemImagePath}challenge-reroll-token.png`,
        kind: 'utility',
        name: 'Challenge Reroll Token',
        rankRequirement: 'D',
        repeatable: true,
      },
      {
        cost: 750,
        effect: 'For 24 hours, get +10% Essence from all gains.',
        id: 'lucky-crystal',
        image: `${itemImagePath}lucky-crystal.png`,
        kind: 'boost',
        name: 'Lucky Crystal',
        rankRequirement: 'D',
        repeatable: true,
      },
      {
        cost: 2000,
        effect: 'Protect your streak once and gain bonus Essence when it triggers.',
        id: 'momentum-crystal',
        image: `${itemImagePath}momentum-crystal.png`,
        kind: 'protection',
        name: 'Momentum Crystal',
        rankRequirement: 'D',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Vanguard Arsenal',
    description: 'Boss challenge access and chain systems begin at C Rank.',
    id: 'c-rank',
    rankRequirement: 'C',
    title: 'C Rank Arsenal',
    items: [
      {
        cost: 1000,
        effect: 'Unlock a Fitness Boss challenge, like completing 5 workouts this week.',
        id: 'goblin-kings-gate-key',
        image: `${itemImagePath}goblin-kings-gate-key.png`,
        kind: 'key',
        name: "Goblin King's Gate Key",
        rankRequirement: 'C',
        repeatable: true,
      },
      {
        cost: 1000,
        effect: 'Unlock a Focus Boss challenge, like completing 10 deep work sessions.',
        id: 'deep-work-gate-key',
        image: `${itemImagePath}deep-work-gate-key.png`,
        kind: 'key',
        name: 'Deep Work Gate Key',
        rankRequirement: 'C',
        repeatable: true,
      },
      {
        cost: 1000,
        effect: 'Unlock an Endurance Boss challenge, like walking 50km this week.',
        id: 'iron-trial-key',
        image: `${itemImagePath}iron-trial-key.png`,
        kind: 'key',
        name: 'Iron Trial Key',
        rankRequirement: 'C',
        repeatable: true,
      },
      {
        cost: 1200,
        effect: 'Until reset, your next three completed challenges gain +50% XP.',
        id: 'challenge-chain',
        image: `${itemImagePath}challenge-chain.png`,
        kind: 'utility',
        name: 'Challenge Chain',
        rankRequirement: 'C',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Elite Arsenal',
    description: 'Risk-reward progression systems unlock at B Rank.',
    id: 'b-rank',
    rankRequirement: 'B',
    title: 'B Rank Arsenal',
    items: [
      {
        cost: 3000,
        effect: 'Unlock a difficult weekly progression trial with massive rewards if you clear it before reset.',
        id: 'trial-of-ascension',
        image: `${itemImagePath}trial-of-ascension.png`,
        kind: 'trial',
        name: 'Trial of Ascension',
        rankRequirement: 'B',
        repeatable: true,
      },
      {
        cost: 1500,
        effect: 'Choose a seven-day specialization oath for +50% XP in one category; miss one day and it fails.',
        id: 'hunters-oath',
        image: `${itemImagePath}hunters-oath.png`,
        kind: 'boost',
        name: "Hunter's Oath",
        rankRequirement: 'B',
        repeatable: true,
      },
      {
        cost: null,
        costLabel: 'Variable',
        effect: 'Risk Essence for larger rewards; success returns more, failure loses the investment.',
        id: 'essence-gamble',
        image: `${itemImagePath}essence-gamble.png`,
        kind: 'utility',
        name: 'Essence Gamble',
        rankRequirement: 'B',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Ascendant Arsenal',
    description: 'Legendary-level challenge transformations for A Rank hunters.',
    id: 'a-rank',
    rankRequirement: 'A',
    title: 'A Rank Arsenal',
    items: [
      {
        cost: 5000,
        effect: 'Unlock an extremely difficult legendary weekly objective for massive rewards.',
        id: 'legendary-trial',
        image: `${itemImagePath}legendary-trial.png`,
        kind: 'trial',
        name: 'Legendary Trial',
        rankRequirement: 'A',
        repeatable: true,
      },
      {
        cost: 2500,
        effect: 'Transform your next completed challenge into a legendary reward burst worth 5x XP and 5x Essence.',
        id: 'legendary-contract',
        image: `${itemImagePath}legendary-contract.png`,
        kind: 'contract',
        name: 'Legendary Contract',
        rankRequirement: 'A',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Mythic Arsenal',
    description: 'Legacy-defining systems for S Rank hunters.',
    id: 's-rank',
    rankRequirement: 'S',
    title: 'S Rank Arsenal',
    items: [
      {
        cost: 10000,
        effect: 'Unlock the hardest solo challenge currently available for exceptional rewards.',
        id: 'mythic-trial',
        image: `${itemImagePath}mythic-trial.png`,
        kind: 'trial',
        name: 'Mythic Trial',
        rankRequirement: 'S',
        repeatable: true,
      },
      {
        cost: 5000,
        effect: 'Choose a permanent specialization path that unlocks unique daily and weekly legacy objectives.',
        id: 'hunter-legacy',
        image: `${itemImagePath}hunter-legacy.png`,
        kind: 'prestige',
        name: 'Hunter Legacy',
        rankRequirement: 'S',
        repeatable: false,
      },
      {
        cost: 3000,
        effect: 'Unlock advanced boss encounters with superior rewards.',
        id: 'master-boss-key',
        image: `${itemImagePath}master-boss-key.png`,
        kind: 'key',
        name: 'Master Boss Key',
        rankRequirement: 'S',
        repeatable: true,
      },
    ],
  },
  {
    arsenalName: 'Paragon Arsenal',
    description: 'Prestige cosmetics that display achievement without major power gains.',
    id: 'ss-rank',
    rankRequirement: 'SS',
    title: 'SS Rank Arsenal',
    items: [
      {
        cost: 4000,
        effect: 'Wrap your avatar in an exclusive SS prestige plate and upgrade your name treatment.',
        id: 'paragon-nameplate',
        image: `${itemImagePath}paragon-nameplate.png`,
        kind: 'prestige',
        name: 'Paragon Nameplate',
        rankRequirement: 'SS',
        repeatable: false,
      },
      {
        cost: 8000,
        effect: 'Create a rank showcase pedestal for progression history and achievements.',
        id: 'rank-showcase-pedestal',
        image: `${itemImagePath}rank-showcase-pedestal.png`,
        kind: 'prestige',
        name: 'Rank Showcase Pedestal',
        rankRequirement: 'SS',
        repeatable: false,
      },
    ],
  },
  {
    arsenalName: 'Iterated One Arsenal',
    description: 'Final prestige rewards representing complete mastery and dedication.',
    id: 'sss-rank',
    rankRequirement: 'SSS',
    title: 'SSS Rank Arsenal',
    items: [
      {
        cost: 15000,
        effect: 'Wrap your avatar in the ultimate SSS prestige plate with a living celestial name treatment.',
        id: 'living-nameplate',
        image: `${itemImagePath}living-nameplate.png`,
        kind: 'prestige',
        name: 'Living Nameplate',
        rankRequirement: 'SSS',
        repeatable: false,
      },
      {
        cost: 25000,
        effect: 'Display rank history, boss victories, trials, and XP in a permanent legendary showcase.',
        id: 'hall-of-legends-monument',
        image: `${itemImagePath}hall-of-legends-monument.png`,
        kind: 'prestige',
        name: 'Hall of Legends Monument',
        rankRequirement: 'SSS',
        repeatable: false,
      },
      {
        cost: 20000,
        effect: 'Own a rare prestige collectible artifact with no gameplay advantage.',
        id: 'founders-relic',
        image: `${itemImagePath}founders-relic.png`,
        kind: 'prestige',
        name: "Founder's Relic",
        rankRequirement: 'SSS',
        repeatable: false,
      },
    ],
  },
];

export const SHOP_ITEMS = SHOP_SECTIONS.flatMap((section) => section.items);

export function getShopItemById(itemId: string) {
  return SHOP_ITEMS.find((item) => item.id === itemId) ?? null;
}

export function getRankRequirementOrder(rankRequirement: ShopRankRequirement) {
  if (rankRequirement === 'core') {
    return 1;
  }

  return RANKS.find((rank) => rank.name === rankRequirement)?.order ?? 1;
}

export function getRankRequirementLabel(rankRequirement: ShopRankRequirement) {
  return rankRequirement === 'core' ? 'Available to all ranks' : `Requires Rank ${rankRequirement}`;
}
