import type { AchievementDefinition } from './achievementTypes';

const rankImagePath = '/assets/ranks/';
const shopImagePath = '/assets/shop/items/';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    category: 'challenge',
    description: 'Complete your first challenge.',
    essenceReward: 100,
    id: 'first-iteration',
    image: `${shopImagePath}bonus-challenge-scroll.png`,
    name: 'First Iteration',
    rewardItemId: 'bonus-challenge-scroll',
  },
  {
    category: 'challenge',
    description: 'Complete 10 challenges.',
    essenceReward: 250,
    id: 'steady-spark',
    image: `${shopImagePath}challenge-chain.png`,
    name: 'Steady Spark',
  },
  {
    category: 'challenge',
    description: 'Complete 50 challenges.',
    essenceReward: 750,
    id: 'forged-discipline',
    image: `${shopImagePath}elite-contract.png`,
    name: 'Forged Discipline',
    rewardItemId: 'double-xp-sigil',
  },
  {
    category: 'challenge',
    description: 'Complete 100 challenges.',
    essenceReward: 1500,
    id: 'hundredfold-path',
    image: `${shopImagePath}hall-of-legends-monument.png`,
    name: 'Hundredfold Path',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'streak',
    description: 'Reach a 3 day streak.',
    essenceReward: 100,
    id: 'ember-streak',
    image: `${shopImagePath}iron-will-token.png`,
    name: 'Ember Streak',
  },
  {
    category: 'streak',
    description: 'Reach a 7 day streak.',
    essenceReward: 350,
    id: 'week-flame',
    image: `${shopImagePath}focus-lens.png`,
    name: 'Week Flame',
    rewardItemId: 'focus-lens',
  },
  {
    category: 'streak',
    description: 'Reach a 30 day streak.',
    essenceReward: 1500,
    id: 'unbroken-month',
    image: `${shopImagePath}streak-shield.png`,
    name: 'Unbroken Month',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'rank',
    description: 'Reach Rank D.',
    essenceReward: 150,
    id: 'rank-d',
    image: `${rankImagePath}rank-d.png`,
    name: 'Bronze Gate',
  },
  {
    category: 'rank',
    description: 'Reach Rank C.',
    essenceReward: 300,
    id: 'rank-c',
    image: `${rankImagePath}rank-c.png`,
    name: 'Silver Gate',
    rewardItemId: 'double-xp-sigil',
  },
  {
    category: 'rank',
    description: 'Reach Rank B.',
    essenceReward: 600,
    id: 'rank-b',
    image: `${rankImagePath}rank-b.png`,
    name: 'Violet Vanguard',
  },
  {
    category: 'rank',
    description: 'Reach Rank A.',
    essenceReward: 1000,
    id: 'rank-a',
    image: `${rankImagePath}rank-a.png`,
    name: 'Sapphire Elite',
    rewardItemId: 'double-xp-sigil',
  },
  {
    category: 'rank',
    description: 'Reach Rank S.',
    essenceReward: 1500,
    id: 'rank-s',
    image: `${rankImagePath}rank-s.png`,
    name: 'Golden Sovereign',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'rank',
    description: 'Reach Rank SS.',
    essenceReward: 2500,
    id: 'rank-ss',
    image: `${rankImagePath}rank-ss.png`,
    name: 'Mythic Paragon',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'rank',
    description: 'Reach Rank SSS.',
    essenceReward: 5000,
    id: 'rank-sss',
    image: `${rankImagePath}rank-sss.png`,
    name: 'Celestial Ascendant',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'guild',
    description: 'Join any guild.',
    essenceReward: 200,
    id: 'guild-initiate',
    image: `${shopImagePath}crystal-banner.png`,
    name: 'Hall Initiate',
    rewardItemId: 'focus-lens',
  },
  {
    category: 'guild',
    description: 'Found your own guild.',
    essenceReward: 500,
    id: 'guild-founder',
    image: `${shopImagePath}founders-relic.png`,
    name: 'Banner Founder',
  },
  {
    category: 'guild',
    description: 'Contribute to a guild boss that gets defeated.',
    essenceReward: 1000,
    id: 'boss-breaker',
    image: `${shopImagePath}master-boss-key.png`,
    name: 'Boss Breaker',
    rewardItemId: 'double-xp-sigil',
  },
  {
    category: 'guild',
    description: 'Complete a guild project with your guild.',
    essenceReward: 1000,
    id: 'project-forger',
    image: `${shopImagePath}rank-showcase-pedestal.png`,
    name: 'Sky Forge Mason',
    rewardItemId: 'streak-shield',
  },
  {
    category: 'shop',
    description: 'Buy any Core Shop item.',
    essenceReward: 200,
    id: 'armory-initiate',
    image: `${shopImagePath}double-xp-sigil.png`,
    name: 'Armory Initiate',
  },
  {
    category: 'shop',
    description: 'Buy any rank-exclusive shop item.',
    essenceReward: 500,
    id: 'rank-arsenal',
    image: `${shopImagePath}goblin-kings-gate-key.png`,
    name: 'Rank Arsenal',
    rewardItemId: 'bonus-challenge-scroll',
  },
];
